services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        networks:
            - my_network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_URL:
                    # IP here

        ports:
            - "3000:3000"

        depends_on:
            - backend

        networks:
            - my_network

networks:
    my_network:
        driver: bridge
