services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.golang
        ports:
            - "3001:3001"
        networks:
            - my_network
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.next
            args:
                NEXT_PUBLIC_API_URL: http://backend:3001

        ports:
            - "3000:3000"

        depends_on:
            - backend

        networks:
            - my_network

networks:
    my_network:
        driver: bridge
