FROM node:22-bookworm

WORKDIR /app
# Copy the package.json file
COPY package*.json ./

RUN npm install

COPY src ./src
COPY next.config.mjs .
COPY postcss.config.mjs .
COPY tailwind.config.ts .
COPY tsconfig.json .

EXPOSE 3000

ARG API_URL

ENV API_URL=$API_URL

RUN npm run build

CMD ["npm", "run", "start"]